version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      # AGE配置
      - AGENSGRAPH_GRAPH_PATH=/var/lib/postgresql/data/ag_graphs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres -c shared_preload_libraries=pg_jieba.so,vector.so,age.so -c search_path=ag_catalog,"$user",public

volumes:
  pg_data:
